namespace MyPortalStudent.Domain {
public class PerfilDTO
{
    public required string idBanner { get; set; }
    public required string pidm { get; set; }
    public required string codLineaNegocio { get; set; }
    public required string codAlumno { get; set; }
    public required string codPersona { get; set; }
    public required string codUsuario { get; set; }
    public required string codSede { get; set; }
    public required string apePatImag { get; set; }
    public required string apeMatImag { get; set; }
    public required string nombresImag { get; set; }
    public required string tipoDocumento { get; set; }
    public required string documenIdentida { get; set; }
    public required string codModalidadEstActual { get; set; }
    public required string codPeriodoActual { get; set; }
    public required string codPeriodoBanner { get; set; }
    public required string codPeriodoBannerCatalogo { get; set; }
    public required string codProductoActual { get; set; }
    public required string codPrograma { get; set; }
    public required string codNivel { get; set; }
    public required string desNivel { get; set; }
    public required string codCampus { get; set; }
    public required string desCampus { get; set; }
    public required string codEstadoAlumno { get; set; }
    public required string desEstadoAlumno { get; set; }
    public required string codTipoAlumno { get; set; }
    public required string desTipoAlumno { get; set; }
    public required string codTipoAprendizaje { get; set; }
    public required string desTipoAprendizaje { get; set; }
    public required string codTipoIngreso { get; set; }
    public required string desTipoIngreso { get; set; }
    public required string desProducto { get; set; }
    public required string desPrograma { get; set; }
    public required string usuarioEmail { get; set; }
    public required string facultad { get; set; }
    public required string facultadId { get; set; }
    public required string fotoUrl { get; set; }
    public required string fechaNacimiento { get; set; }
    public required string sexo { get; set; }
    public required string telefono { get; set; }
    public required string celular { get; set; }
    public required string ciudad { get; set; }
    public required string direccion { get; set; }
    public required string egresado { get; set; }
    public required string ciclo { get; set; }
    public required string fullName { get; set; }
    public required string tipoPersona { get; set; }
    public required string codTipoUsuario { get; set; }
    public required string correoPersonal { get; set; }
    public required string cicloIngreso { get; set; }
    public required string fotoUrlLow { get; set; }
    public required string urbanizacion { get; set; }
    public required string departamento { get; set; }
    public required string distrito { get; set; }
    public required string contactoDeEmergenciaNombre { get; set; }
    public required string contactoDeEmergenciaApellido { get; set; }
    public required string contactoDeEmergenciaCelular { get; set; }
    public required string situacionLaboral { get; set; }
    public required string tipoDeEmpleo { get; set; }
    public required string modalidadEmpleo { get; set; }
    public required string empresa { get; set; }
    public required string ruc { get; set; }
    public required string direccionEmpresa { get; set; }
    public required string cargo { get; set; }
    public required string enlaceLinkedin { get; set; }
    public required string infoJefeNombre { get; set; }
    public required string infoJefeCargo { get; set; }
    public required string infoJefeCorreo { get; set; }
    public required string infoJefeTelefono { get; set; }
    public required string zipCode { get; set; }
    public required string status { get; set; }
    public required string presentationLetterStatusId { get; set; }
    public required string phoneHome { get; set; }
    public required Boolean? autorizaAdicionales { get; set; }
    public required Boolean? autorizaAlumni { get; set; }
    public required Boolean? autorizaDatosPersonales { get; set; }
}
}
